config/routes.rb
Rails.application.routes.draw do
  get 'select_optimal_packages', to: 'package_selectors#select_optimal_packages'
  resources :products
  resources :orders
  resources :packages

  root to: redirect('/products')
  match '*path', to: 'application#not_found', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products
  has_many :products, through: :order_products
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/package.rb
class Package < ApplicationRecord
  has_many :package_product, dependent: :destroy
  has_many :products, through: :package_product

  validates :name, uniqueness: true, presence: true
end

app/models/package_product.rb
class PackageProduct < ApplicationRecord
  belongs_to :product
  belongs_to :package
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_products
  has_many :orders, through: :order_products

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActionController::ParameterMissing, with: :parameter_missing

  private

  def parameter_missing(e)
    render json: { error: e.message }, status: :bad_request
  end

  def not_found
    render file: "#{Rails.root}/public/404.html", status: :not_found
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      flash[:success] = 'Order was successfully created.'
      redirect_to @order
    else
      flash.now[:error] = @order.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @order.update(order_params)
      flash[:success] = 'Order was successfully updated.'
      redirect_to @order
    else
      flash.now[:error] = @order.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_path
  end

  private

  def find_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(product_ids: [])
  end
end

app/controllers/package_selectors_controller.rb
class PackageSelectorsController < ApplicationController

  def select_optimal_packages
    shipment = PackageSelector.select_optimal_packages(order_products, available_packages)

    if shipment && shipment.any?
      render json: { shipment_packages: shipment }
    else
      render json: { error: 'No valid packages found' }, status: :not_found
    end
  end

  private

  def order
    @order ||= Order.find(params[:order_id])
  end

  def order_products
    @order_products ||= order.products.pluck(:name)
  end

  def available_packages
    @available_packages ||= Package.all.map do |package|
      { package.name => package.products.pluck(:name) }
    end
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :find_package, only: [:show, :edit, :update, :destroy]

  def index
    @packages = Package.all
  end

  def show
  end

  def new
    @package = Package.new
  end

  def create
    @package = Package.new(package_params)
    if @package.save
      flash[:success] = 'Package was successfully created.'
      redirect_to @package
    else
      flash.now[:error] = @package.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @package.update(package_params)
      flash[:success] = 'Package was successfully updated.'
      redirect_to @package
    else
      flash.now[:error] = @package.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @package.destroy
    redirect_to packages_path
  end

  private

  def find_package
    @package = Package.find(params[:id])
  end

  def package_params
    params.require(:package).permit(:name ,product_ids: [])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = 'Product was successfully created.'
      redirect_to @product
    else
      flash.now[:error] = @product.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:success] = 'Product was successfully updated.'
      redirect_to @product
    else
      flash.now[:error] = @product.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :success
      "success"
    when :error
      "danger"
    when :alert
      "warning"
    when :notice
      "info"
    else
      flash_type.to_s
    end
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= bootstrap_class_for(type) %>">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Careviso</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="/orders">Orders</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/packages">Packages</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/products">Products</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarevisoTakeHome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/orders/_form.html.erb
<div class="form-container">
<%= form_for @order, html: { class: 'mt-5' } do |f| %>
  <h3 class="mb-4">Select Products for this Order:</h3>
  
  <div class="mb-3">
    <%= f.label :product_ids, "Products", class: 'form-label' %>
    <%= f.collection_select :product_ids, Product.all, :id, :name, {}, { multiple: true, id: 'products-select', class: 'form-select', required: true } %>
  </div>

  <div class="mb-3">
    <%= f.submit "Submit Order", class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/orders/_packages_modal.html.erb
<div class="modal fade" id="packagesModal" tabindex="-1" role="dialog" aria-labelledby="packagesModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="packagesModalLabel">Packages for Order ID: <span id="orderId"></span></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="packagesContent">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<div class="container mt-5">
  <h1 class="display-4 text-center mb-5">Edit Order</h1>
<%= render 'form' %>
</div>

app/views/orders/index.html.erb
<div class="container mt-5">
  <h1 class="display-4 text-center mb-5">All Orders</h1>

<table class="table table-striped table-hover">
  <thead class="thead-light">
    <tr>
      <th>Order ID</th>
      <th>Products</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.products.map(&:name).join(', ') %></td>
        <td>
          <%= link_to 'Edit', edit_order_path(order), class: 'btn btn-warning btn-sm' %>
          <%= link_to 'Delete', order, method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: "Are you sure you want to delete this order?" } %>
          <%= link_to 'Show Packages', '#', class: 'btn btn-info btn-sm', data: { toggle: "modal", target: "#packagesModal", order_id: order.id } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Order', new_order_path, class: 'btn btn-primary mb-3' %>

<%= render 'packages_modal' %>
</div>

app/views/orders/new.html.erb
<div class="container mt-5">
  <h1 class="display-4 text-center mb-5">New Order</h1>
  <%= render 'form' %>
</div>

app/views/orders/show.html.erb
<div class="container mt-5">
  <h1 class="display-4 text-center mb-5">Order Details</h1>

  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">Order ID: <%= @order.id %></h5>
      <p class="card-text">
        Products: <%= @order.products.map(&:name).join(', ') %>
      </p>
    </div>
  </div>

  <div class="text-center">
    <%= link_to 'Edit', edit_order_path(@order), class: 'btn btn-warning btn-sm mr-2' %> 
    <%= link_to 'Delete', @order, method: :delete, class: 'btn btn-danger btn-sm' %> 
  </div>
</div>

app/views/products/_form.html.erb
<div class="form-container">
  <%= form_for @product, html: { class: 'mt-5' } do |f| %>
    <h3 class="mb-4">New Product</h3>

    <div class="mb-3">
      <%= f.label :name, "Product Name", class: 'form-label' %>
      <%= f.text_field :name, class: 'form-control', required: true %>
    </div>

    <div class="mb-3">
      <%= f.submit "Create Product", class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="container mt-5">
  <h1 class="display-4 text-center mb-5">Edit Product</h1>
<%= render 'form' %>
</div>

app/views/products/index.html.erb
<div class="container mt-5">
  <h1 class="display-4 text-center mb-5">All Products</h1>

<table class="table table-striped table-hover">
  <thead class="thead-light">
    <tr>
      <th>Product ID</th>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.name %></td>
        <td>
          <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-warning btn-sm' %>
          <%= link_to 'Delete', product, method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: "Are you sure you want to delete this product?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Product', new_product_path, class: 'btn btn-primary mb-3' %>
</div>

app/views/products/new.html.erb
<div class="container mt-5">
  <h1 class="display-4 text-center mb-5">New Product</h1>
  <%= render 'form' %>
</div>

app/views/products/show.html.erb
<div class="container mt-5">

  <h1 class="display-4 text-center mb-5">Product Detail</h1>

  <div class="card mb-4">
    <div class="card-body">
      <h5 class="card-title">Package ID: <%= @product.id %></h5>
      <p class="card-text">
        Name: <%= @product.name %>
      </p>
    </div>
  </div>

  <div class="text-center">
    <%= link_to 'Edit', edit_product_path(@product), class: 'btn btn-warning btn-sm mr-2' %> 
    <%= link_to 'Delete', @product, method: :delete, class: 'btn btn-danger btn-sm' %> 
  </div>

</div>